### ISSUE TITLE
Bolt Python wrapper doesn't build on some systems

### ISSUE THREAD

**Issue by dblalock** [dblalock/bolt#4]
At present, Bolt's python code doesn't appear to be building on Ubuntu and hasn't been tested on Windows. It may also have issues building on other systems.

**Comment by arminbashizade** [comment]
I could build the code on redhat with this modifications:

- include stdint.h in cpp/src/quantize/bolt.hpp
- use swig 3.0
- compile with clang 3.9 (in setup.py: extra_args = ['std=c++1y', '-stdlib=libc++', ...]

now my problem is when I try to import bolt I get this error:

```python
>>> import bolt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python2.7/site-packages/pybolt-0.1.4-py2.7-linux-x86_64.egg/bolt/__init__.py", line 5, in <module>
    from bolt_api import *  # noqa
  File "~/.local/lib/python2.7/site-packages/pybolt-0.1.4-py2.7-linux-x86_64.egg/bolt/bolt_api.py", line 6, in <module>
    import bolt  # inner bolt because of SWIG
  File "~/.local/lib/python2.7/site-packages/pybolt-0.1.4-py2.7-linux-x86_64.egg/bolt/bolt.py", line 17, in <module>
    _bolt = swig_import_helper()
  File "~/.local/lib/python2.7/site-packages/pybolt-0.1.4-py2.7-linux-x86_64.egg/bolt/bolt.py", line 16, in swig_import_helper
    return importlib.import_module('_bolt')
  File "~/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: ~/.local/lib/python2.7/site-packages/pybolt-0.1.4-py2.7-linux-x86_64.egg/_bolt.so: undefined symbol: _ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv

```

**Comment by arminbashizade** [comment]
setting the environment variable LDFLAGS to -lc++ solved the problem. (adding os.environ['LDFLAGS'] = '-lc++' to setup.py)

**Comment by dblalock** [comment]
I marked this as closed by adding your changes as per our email exchange. Thanks for your help in getting to the bottom of this. For those seeing this in the future, I'm not 100% certain this fix will work on all systems and so would be happy to reopen this if you have problems.

**Comment by goobee** [comment]
Hi,i miss a problem when i install Bolt

> In file included from python/bolt/native_wrap.cpp:173:
In file included from /usr/include/python2.7/Python.h:19:
/usr/include/limits.h:125:16: fatal error: 'limits.h' file not found
# include_next <limits.h>

**Comment by goobee** [comment]
Hi,I miss a problem when i install Bolt

`In file included from python/bolt/native_wrap.cpp:173:
In file included from /usr/include/python2.7/Python.h:19:
/usr/include/limits.h:125:16: fatal error: 'limits.h' file not found
# include_next <limits.h>
`
how can i fix it

**Comment by goobee** [comment]
_In file included from python/bolt/native_wrap.cpp:173:
In file included from /usr/include/python2.7/Python.h:19:
/usr/include/limits.h:125:16: fatal error: 'limits.h' file not found
# include_next <limits.h>
_

**Comment by goobee** [comment]
hi,when i install Bolt i miss a problem
![image](https://user-images.githubusercontent.com/42989762/45069737-8b4d1080-b100-11e8-9c83-60558d7740ca.png)

**Comment by goobee** [comment]
I miss another problem look like this
_python/bolt/../../cpp/src/include/public.hpp:23: Warning 315: Nothing known about 'std::vector'.
python/bolt/config.i:45: Warning 315: Nothing known about 'Eigen::Matrix'.
python/bolt/config.i:46: Warning 315: Nothing known about 'Eigen::Dynamic'.
python/bolt/config.i:46: Warning 315: Nothing known about 'Eigen::Dynamic'.
python/bolt/config.i:47: Warning 315: Nothing known about 'Eigen::RowMajor'.
python/bolt/config.i:45: Warning 315: Nothing known about 'Eigen::Matrix'.
python/bolt/config.i:46: Warning 315: Nothing known about 'Eigen::Dynamic'.
python/bolt/config.i:46: Warning 315: Nothing known about 'Eigen::Dynamic'.
python/bolt/config.i:47: Warning 315: Nothing known about 'Eigen::RowMajor'.
clang -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DNDEBUG=1 -I/home/public/anaconda3/lib/python3.6/site-packages/numpy/core/include -Icpp/src/quantize -Icpp/src/utils -Icpp/src/include -Icpp/src/external -Icpp/src/external/eigen -I/home/yhx/bolt/python/bolt -I/home/public/anaconda3/include/python3.6m -c python/bolt/native_wrap.cpp -o build/temp.linux-x86_64-3.6/python/bolt/native_wrap.o -std=c++14 -fno-rtti -march=native -ffast-math -std=c++11 -stdlib=libc++
python/bolt/native_wrap.cpp:3053:10: fatal error: 'stdexcept' file not found
#include <stdexcept>
         ^
1 error generated.
error: command 'clang' failed with exit status 1_

**Comment by dblalock** [comment]
This might be an issue with the stdlib that you're using. Can you build the following simple program?

main.cpp
    #include <stdexcept>
    int main() { return 0; }

with
    $ clang++ main.cpp -o main.out -std=c++14 -stdlib=libc++

I also just removed the duplicate `std=` flags from the configuration, which may have caused problems.

**Comment by dblalock** [comment]
Great. Now what happens when you instead use a different stdlib? I.e.:

    $ clang++ main.cpp -o main.out -std=c++14 -stdlib=libstdc++
or 

    $ clang++ main.cpp -o main.out -std=c++14 -stdlib=libstdc++

Also, what do you get when you do:

    $ clang -v

**Comment by goobee** [comment]
hello,when i follow those two  command ,
$ clang++ main.cpp -o main.out -std=c++14 -stdlib=libstdc++
$ clang++ main.cpp -o main.out -std=c++14
I got the same error

`[root@localhost bolt]# clang++ main.cpp -o main.out -std=c++14 -stdlib=libstdc++
In file included from main.cpp:1:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/stdexcept:39:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/string:40:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/char_traits.h:40:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/postypes.h:40:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/cwchar:44:
/usr/include/wchar.h:39:11: fatal error: 'stdarg.h' file not found
# include <stdarg.h>
1 error generated.
[root@localhost bolt]# clang -v
clang version 3.9.1 (tags/RELEASE_391/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
`

**Comment by dblalock** [comment]
Hmm. Based on what's [here](https://stackoverflow.com/questions/20206290/fatal-error-stdarg-h-file-not-found), can you compile a one-line cpp file that just contains:

     #include <cstdarg>

Also, if I'm counting the `..`s properly, it appears to be searching in `/usr/include/c++/4.8.5/` for all of your headers. [This issue](https://github.com/include-what-you-use/include-what-you-use/issues/369) suggests that this header is supposed to get added when you install clang. Do you see `stdarg.h` in that directory? If not, what about when you do:

    $ find /usr/include -name 'stdarg.h'

Also, for the sake of others seeing this thread, I edited your post so the error messages appear as code and the "include" doesn't look like a header. Hope that's okay. You can make it look like code by indenting four spaces or wrapping in the "`" (backtick) character.

**Comment by drscotthawley** [comment]
Tried to get this to work on Colab, but got "unterminated string contsant" build error from swig after `cd bolt && python setup.py install`:

```
swigging cpp/src/external/eigen/.hg/store/data/_c_test_config.cmake.i to cpp/src/external/eigen/.hg/store/data/_c_test_config.cmake_wrap.cpp
swig -python -c++ -o cpp/src/external/eigen/.hg/store/data/_c_test_config.cmake_wrap.cpp cpp/src/external/eigen/.hg/store/data/_c_test_config.cmake.i
cpp/src/external/eigen/.hg/store/data/_c_test_config.cmake.i:3: Error: Unterminated string constant
error: command 'swig' failed with exit status 1
```

My minimal Colab example link is here: https://colab.research.google.com/drive/1ATN8-R4xqghk9faNBqxFoE28iKd7WCZp?usp=sharing

**Comment by pengxia24** [comment]
use python3 to install bolt, but failed
```
swigging cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in.i to cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in_wrap.cpp
swig -python -c++ -o cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in_wrap.cpp cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in.i
cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in.i:1: Error: Illegal token '�'.
cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in.i:1: Error: Syntax error in input(1).
error: command 'swig' failed with exit status 1
```

**Comment by mrjzz** [comment]
> Tried to get this to work on Colab, but got "unterminated string constant" build error from swig after `cd bolt && python setup.py install`:
> 
> ```
> swigging cpp/src/external/eigen/.hg/store/data/_c_test_config.cmake.i to cpp/src/external/eigen/.hg/store/data/_c_test_config.cmake_wrap.cpp
> swig -python -c++ -o cpp/src/external/eigen/.hg/store/data/_c_test_config.cmake_wrap.cpp cpp/src/external/eigen/.hg/store/data/_c_test_config.cmake.i
> cpp/src/external/eigen/.hg/store/data/_c_test_config.cmake.i:3: Error: Unterminated string constant
> error: command 'swig' failed with exit status 1
> ```
> 
> My minimal Colab example link is here: https://colab.research.google.com/drive/1ATN8-R4xqghk9faNBqxFoE28iKd7WCZp?usp=sharing

I encounter this error with my Ubuntu likewise. 
It seem to be caused by  the upgrade of swig's version up to 4.0 (my swig version in ubuntu is 4.0).But I am not sure.
THere is a  similar bug:
https://github.com/InsightSoftwareConsortium/ITK/issues/2026

**Comment by husisy** [comment]
I guess the folder `cpp/src/external/eigen/.hg` is managed by the software Mercurial (something like git) which will lead to the issue `Unterminated string constant`, so I simply delete this folder to go on the installation.

Then, I struggle with the issue "command clang not exist" on Ubuntu. To solve this, I turn to run this code on Mac.

Also, in `setup.py`, some items included in the list `srcFiles` will cause swig to fail, so I add modified several lines in it like below

```Python
exclude_file_ext = ['.cxxlist','.cu','.cmake','.in','.css','.entry','.evaluator','.expression','.main','.preamble','.traits']
srcFiles += [x for x in files if not any(x.endswith(y) for y in exclude_file_ext)]
```

After all above, it seems start to build the project, but fail agian...... The error is like below and I have no idea now...

```bash
  In file included from cpp/src/external/eigen-trimmed/unsupported/doc/examples/PolynomialSolver1.cpp:1:
  In file included from cpp/src/external/eigen-trimmed/unsupported/Eigen/Polynomials:40:
  cpp/src/external/eigen-trimmed/unsupported/Eigen/src/Polynomials/PolynomialSolver.h:365:43: error: no member named 'abs' in namespace 'Eigen::numext'; did you mean simply 'abs'?
            if( internal::isMuchSmallerThan(numext::abs(numext::imag(m_roots[i])),
                                            ^~~~~~~~~~~
                                            abs
  cpp/src/external/eigen-trimmed/Eigen/src/Core/GlobalFunctions.h:58:36: note: 'abs' declared here
    EIGEN_ARRAY_DECLARE_GLOBAL_UNARY(abs,scalar_abs_op)
                                     ^
  In file included from cpp/src/external/eigen-trimmed/unsupported/doc/examples/PolynomialSolver1.cpp:1:
  In file included from cpp/src/external/eigen-trimmed/unsupported/Eigen/Polynomials:40:
  cpp/src/external/eigen-trimmed/unsupported/Eigen/src/Polynomials/PolynomialSolver.h:366:43: error: no member named 'abs' in namespace 'Eigen::numext'; did you mean simply 'abs'?
                                            numext::abs(numext::real(m_roots[i])),
                                            ^~~~~~~~~~~
                                            abs
  cpp/src/external/eigen-trimmed/Eigen/src/Core/GlobalFunctions.h:58:36: note: 'abs' declared here
    EIGEN_ARRAY_DECLARE_GLOBAL_UNARY(abs,scalar_abs_op)
                                     ^
  In file included from cpp/src/external/eigen-trimmed/unsupported/doc/examples/PolynomialSolver1.cpp:1:
  In file included from cpp/src/external/eigen-trimmed/unsupported/Eigen/Polynomials:40:
```

**Comment by drscotthawley** [comment]
On Ubuntu, after following @husisy's advice and removing `eigen`'s `.hg/` folder, I start getting a series of "unknown file type" errors, such as:

```
error: unknown file type '.cmake' (from 'cpp/src/external/eigen/CTestConfig.cmake')
```
^on Colab, and on my Pop_OS (Ubuntu variant) laptop I get:
```
error: unknown file type '.cu' (from 'cpp/src/external/eigen-trimmed/unsupported/test/cxx11_tensor_argmax_gpu.cu')
```

If this library is only intended for Mac then sorry, my mistake.  I'll stop trying.

**Comment by drscotthawley** [comment]
Update: Above Colab goes significantly further. than before but still fails.
'Fixed' the above Apple-specific error after reading further up this Issue (woops) by creating a blank file.  Then spent about 7 hours on Saturday.  Seems that `clang` is getting called where `clang++` should be, and that `bolt` code has hard-coded "eigen/Core" where it should read (and other libraries use) "Eigen/Core" or "eigen3/Eigen/Core".  Is this an artifact using a case-unspecific filesystem like Mac?

```
In file included from python/bolt/native_wrap.cpp:3129:
In file included from /content/bolt/python/bolt/../../cpp/src/include/public.hpp:19:
In file included from cpp/src/external/eigen/Eigen/Core:96:
In file included from /usr/include/c++/7.5.0/complex:45:
In file included from /usr/include/c++/7.5.0/sstream:38:
In file included from /usr/include/c++/7.5.0/istream:38:
In file included from /usr/include/c++/7.5.0/ios:42:
In file included from /usr/include/c++/7.5.0/bits/ios_base.h:46:
/usr/include/c++/7.5.0/system_error:94:13: error: unknown type name '__cow_string'
    virtual __cow_string
            ^
/usr/include/c++/7.5.0/system_error:341:36: error: expected class name
  class system_error : public std::runtime_error
                                   ^
/usr/include/c++/7.5.0/system_error:348:7: error: member initializer 'runtime_error' does not name a non-static data member or base class
    : runtime_error(__ec.message()), _M_code(__ec) { }
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/7.5.0/system_error:351:7: error: member initializer 'runtime_error' does not name a non-static data member or base class
    : runtime_error(__what + ": " + __ec.message()), _M_code(__ec) { }
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/7.5.0/system_error:354:7: error: member initializer 'runtime_error' does not name a non-static data member or base class
    : runtime_error(__what + (": " + __ec.message())), _M_code(__ec) { }
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/7.5.0/system_error:360:7: error: member initializer 'runtime_error' does not name a non-static data member or base class
    : runtime_error(error_code(__v, __ecat).message()),
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/7.5.0/system_error:364:7: error: member initializer 'runtime_error' does not name a non-static data member or base class
    : runtime_error(__what + ": " + error_code(__v, __ecat).message()),
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
python/bolt/native_wrap.cpp:3141:12: fatal error: 'eigen/Core' file not found
  #include "eigen/Core"
           ^~~~~~~~~~~~
8 errors generated.
```

@dblalock Let us know when we can try this out! Looking forward to it. Until then, :wave:

**Comment by 362502anct** [comment]
Hello, when I install the bolt on my macbook, I follow the installing process but meet the following problem.
`swigging cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in.i to cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in_wrap.cpp
swig -python -c++ -o cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in_wrap.cpp cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in.i
cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in.i:1: Error: Illegal token '?'.
cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in.i:1: Error: Syntax error in input(1).
error: command 'swig' failed with exit status 1`
Even changing the version of swig can not solve this problem. So I ask what can I do? Thanks.

**Comment by dblalock** [comment]
Thanks for everyone's feedback and work on this. I'm looking into this, but it's kind of slow going at the moment (especially since I'm doing about 70h/week at my day job and don't have much time left over). Appreciate your enthusiasm and patience.

**Comment by calvinmccarter** [comment]
@dblalock With a bit more documentation around the C++ API, I'd be happy to write a basic command-line interface. Obviously getting and returning matrices via file i/o is slow, but it would be sufficient for me.

**Comment by mneilly** [comment]
FWIW - I created a branch (https://github.com/mneilly/bolt/tree/mneilly/fixes) which compiles and runs on both Linux and Mac OS X. Of course, there may be issues with other people's systems as I've only tested it on Debian 11 and Mac OS X 10.14.6....

The primary changes are adding a CMakeLists.txt file, adding a kmc2 submodule from a branch that compiles with python 3 and various fixes to make things run.

**Comment by mneilly** [comment]
FWIW - I have a branch that has changes so that things can be built and run on Linux and Mac. The changes basically add a CMakeLists.txt to build with cmake, add a kmc2 submodule that works with python3 and setup.py changes so the python package builds. There is a build.sh that was tested to work on Debian 11 and Mac OS X 10.14.6.

https://github.com/mneilly/bolt/tree/mneilly/fixes

**Comment by dblalock** [comment]
@mneilly this is awesome, thanks! I'll be happy to merge it if you open a PR.

**Comment by charlswzc** [comment]
@dblalock @mneilly If anybody runs BOLT perfectly, can you you guys share the information of your machine? Like OS version, swig version, and so on. Many thanks!

I tried win10, ubuntu 18.04/20.01, still not working. [sad]

**Comment by windspirit95** [comment]
> @dblalock @mneilly If anybody runs BOLT perfectly, can you you guys share the information of your machine? Like OS version, swig version, and so on. Many thanks!
> 
> I tried win10, ubuntu 18.04/20.01, still not working. [sad]

Finally, I could install Bolt perfectly, with kmc2 install
- Ubuntu version: 18.04
- swig 3.0.12
- Install Bolt: 
```
git clone -b mneilly/fixes https://github.com/mneilly/bolt.git
cd bolt
python setup.py install
cd ../
```
- Install kmc2
```
git clone -b mneilly/cythonize https://github.com/mneilly/kmc2.git
cd kmc2
python setup.py install
cd ../
```
Thanks to @mneilly for the PR ^^

**Comment by dblalock** [comment]
Yes, big thanks to mneilly! For any future readers, I actually merged this branch into Bolt, so in theory you should get the same results in the main repo now.

That said, I would never bet on the robustness of barely-maintained code spanning two languages with legacy FFI interfaces and x86-specific libraries, so worth giving mneilly's branch a try if this repo doesn't work. The docker container he wrote (see [BUILD.md](https://github.com/dblalock/bolt/blob/master/BUILD.md) should be more reliable.
